### ISSUE TITLE
python_http_client issue

### ISSUE THREAD

**Issue by zhenhaoluo** [DittmarLab/HGTector#44]
Hi Qiyun,
I am using the HGTector2 pipeline. When I ran the example, the screen always traceback me a messages showed as follow:
Traceback (most recent call last):
  File "/mdata/luozh/softwares/miniconda/envs/hgtector/lib/python3.7/http/client.py", line 554, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/mdata/luozh/softwares/miniconda/envs/hgtector/lib/python3.7/http/client.py", line 521, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

what's wrong with this? waiting for your repy. thank you very much
Regards

**Comment by tauqeer9** [comment]
Hi
I am also getting same error. Are you able to fix it?

Thanks

**Comment by qiyunzhu** [comment]
@tauqeer9 Thanks for providing this solution! I guess in some Python distributions, the http client is not installed by default (perhaps that's the case for @zhenhaoluo), and your solution is great in that scenario.
