### ISSUE TITLE
message:urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long

### ISSUE THREAD

**Issue by jcogier** [DittmarLab/HGTector#48]
Hi Qiyun,
I am using the HGTector2 pipeline. When I ran my protein imput file.fasta ( 4000 proteins), the screen always traceback me a messages showed as follow with the final error message:urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long
What do you thinck about this problem?
Many thanks for your advice
Best regards
Jean claude

Homology search started at 2020-04-20 14:24:42.412971.
Settings:
  Search method: remote.
  Self-alignment method: native.
  Remote fetch enabled: yes.
Reading input proteins...
  XKB1.1-Proteins: 4050 proteins.
Done. Read 4050 proteins from 1 samples.
Dropping sequences shorter than 30 aa... done.
Reading custom taxonomy database... done.
  Read 1 taxa.
Batch homology search of XKB1.1-Proteins started at 2020-04-20 14:24:42.796838.
Number of queries: 4046.
Submitting 21 queries for search.Traceback (most recent call last):
  File "/home/jogier/anaconda3/envs/hgtector/bin/hgtector", line 100, in <module>
    main()
  File "/home/jogier/anaconda3/envs/hgtector/bin/hgtector", line 39, in main
    module(args)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 165, in __call__
    res = self.search_wf(
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 701, in search_wf
    res = self.remote_search(seqs)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 1599, in remote_search
    with urlopen(url) as response:
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/jogier/anaconda3/envs/hgtector/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long

**Comment by qiyunzhu** [comment]
Hi @jcogier thanks for your interest in our program! The remote BLAST function is not practical if you have a large number of input sequences (i.e., 4000). You will need to build a local database and run search locally. The [install](https://github.com/DittmarLab/HGTector/blob/master/doc/install.md) page explains how you can get the database and aligner.
