### ISSUE TITLE
hgtector search 

### ISSUE THREAD

**Issue by xu-j1234566** [DittmarLab/HGTector#51]
Hi
First thanks for your Hgtector!
I meet error when use 'hgtector search',

Command:
conda create -n hgtector python=3 pyyaml pandas matplotlib scikit-learn
conda activate hgtector
pip install git+https://github.com/DittmarLab/HGTector.git
hgtector search -o ll -i o55h7.faa.gz -d diamond/db.dmnd -t taxdump/ -m diamond

Error:
(hgtector) []$ hgtector search -o ll -i o55h7.faa.gz -d diamond/db.dmnd -t taxdump/ -m diamond
Homology search started at 2020-05-22 08:10:24.825237.
Traceback (most recent call last):
  File "/home/usr/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/usr/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/usr/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 131, in __call__
    self.args_wf(args)
  File "/home/usr/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 330, in args_wf
    if not isdir(dir_):
  File "/home/usr/envs/hgtector/lib/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by qiyunzhu** [comment]
Hello @xu-j1234566 Thanks for your test and sorry for the late response. I have fixed this bug. If you [update](https://github.com/DittmarLab/HGTector/blob/master/doc/install.md#upgrade) the program and run this command again, it should work now.
