### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by 473021677** [DittmarLab/HGTector#52]
Hello
    I have installed HGTector through Conda and used the "ref107" database to test it. But when I typed the command "hgtector search -i o55h7.faa -o /bigdata/yuanyang/software/HGTector-test -m diamond -d /bigdata/yuanyang/software/HGTector-test/diamond/db -t /bigdata/yuanyang/software/HGTector-test/taxdump", it showed the error:
Homology search started at 2020-05-31 21:02:54.802337.
Traceback (most recent call last):
  File "/home/yuanyang/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/yuanyang/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/yuanyang/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 131, in __call__
    self.args_wf(args)
  File "/home/yuanyang/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/search.py", line 330, in args_wf
    if not isdir(dir_):
  File "/home/yuanyang/miniconda3/envs/hgtector/lib/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Could you help me? Thanks for your help very much.

Best regards

**Comment by qiyunzhu** [comment]
Hello @473021677 Thanks for reporting this bug! I have fixed it. If you [update](https://github.com/DittmarLab/HGTector/blob/master/doc/install.md#upgrade) the program and run this command again, it should work now.
