### ISSUE TITLE
_tkinter.TclError: couldn't connect to display "localhost:14.0"

### ISSUE THREAD

**Issue by surh** [DittmarLab/HGTector#54]
I am trying to set up hgtector to run on a set of bacterial genomes in a remote server. I created a conda environment as per the instructions and I was able to run the search part of the [second run](https://github.com/DittmarLab/HGTector/blob/master/doc/2ndrun.md) example. However, when I try to run the analysis part I get the error below

```bash
Analysis started at 2020-06-12 15:16:01.101009.
Reading local taxonomy database...
Done. Read 92 taxa.
Reading homology search results...
  o55h7: 5045 proteins.
Done. Read search results of 1 samples.
Auto-inferring plausible taxIds for input genomes based on taxonomy of search results...
  o55h7: 562 (Escherichia coli) (covering 93.2933% best hits).
Refining taxonomy database...
Done. Retained 92 taxa.
All input genomes belong to 562 (species Escherichia coli).
Auto-inferred self group:
  562 (species Escherichia coli)
Self group has 5 taxa.
Auto-inferred close group:
  543 (family Enterobacteriaceae)
Close group has 15 taxa.
Calculating protein scores by group...
  o55h7
Done.
Summarizing scores of all proteins... done.
Protein scores written to scores.tsv.
Removed 687 ORFans.
Removed 89 outliers.
Predicting HGTs...
Calculating thresholds for clustering...
Close group:
Traceback (most recent call last):
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 160, in __call__
    self.predict_hgt()
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 720, in predict_hgt
    self.plot_hist(self.df[group].tolist(),
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 1027, in plot_hist
    fig = plt.figure(figsize=(5, 5))
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/matplotlib/pyplot.py", line 540, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3337, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 876, in new_figure_manage
r_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/groups/hbfraser/modules/packages/conda/4.6.14/envs/hgtector/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:14.0"
```
My guess is that it is trying to show me some plots but there is no graphical interface in the remote server so it is crashing. Is that correct? can I disable the graphical output?

Thanks

**Comment by qiyunzhu** [comment]
Hello @surh Sorry for the late response. I believe that your guess is correct. I modified the code (#56 ) so that matplotlib will no longer attempt to open a graphical interface which is not available in many remote servers, but it is still capable of generating figures. Please update the program by:

```bash
pip install -U git+https://github.com/DittmarLab/HGTector.git@2.0b2
```

And let me know if it now works for you! If so I will update my master branch. Thank you!

**Comment by surh** [comment]
thanks for looking into this @qiyunzhu, your fix worked!

Thanks,
Sur
