### ISSUE TITLE
An error in hgtector database command

### ISSUE THREAD

**Issue by mtnouchi** [DittmarLab/HGTector#59]
Hello,

I was trying to run the Second run in the doc with a slight modification and encountered an error. 

I ran the following command  : 
`hgtector database -c microbe -t 2 -s 1 -r superkingdom --reference --compile blast -o <hoge>/hgtectordb`

...and received an error message:
```
Traceback (most recent call last):
  File "/.../anaconda3-5.3.1/envs/hgtector/bin/hgtector", line 96, in <module>.
    main()
  File "/.../anaconda3-5.3.1/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/.../anaconda3-5.3.1/envs/hgtector/lib/python3.7/site-packages/hgtector/database.py", line 155, in __ call__.
    self.compile_database()
  File "/.../anaconda3-5.3.1/envs/hgtector/lib/python3.7/site-packages/hgtector/database.py", line 744, in compile_database
    self.build_blast_db()
  File "/.../anaconda3-5.3.1/envs/hgtector/lib/python3.7/site-packages/hgtector/database.py", line 763, in build_blast_db
    raise ValueError(f'makeblastdb failed with error code {ec}.')
ValueError: makeblastdb failed with error code 1.
```

Looking at the internal implementation, I ran the command executed by run_command() for `makeblastdb`:
`makeblastdb -dbtype prot -in hgtectordb/db.faa -out a -title db -parse_seqids -taxid_map hgtectordb/taxon.map.gz`

 and found an error saying
```
Error: NCBI C++ Exception:
    T0 "/.../ncbistr.cpp", line 800: Error: ncbi::NStr::StringToInt8() - Cannot convert string 'Ll_23F?????) ??? ??????????????????????????????????????????????????????????????????????????????????????????) (SP??LA??2e??g???? ?O?8?2e' to Int8 (m_Pos = 0)
```

It seems that `makeblastdb`'s `-taxid_map` does not support gziped files, so it'd be better to store the taxon.map file in its unzipped state.

Best Regards,

**Comment by qiyunzhu** [comment]
@mtnouchi Thank you for reporting this bug! Tested and validated. Fixed in pull request #60 . It should work now.
