### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by caris1988** [DittmarLab/HGTector#63]
Hello,
I created a conda environment (python=3.6.5, and installed the packages pyyaml pandas matplotlib scikit-learn), and then ran the command:
`pip install git+https://github.com/DittmarLab/HGTector.git`
It showed that hgtector installed sucssesfully. But when I typed the command:
`hgtector`
I recieved the error message.
-------------------------------------------------------------
Traceback (most recent call last):
  File "/public/home/chenruolin/.conda/envs/vibrant/bin/hgtector", line 96, in <module>
    main()
  File "/public/home/chenruolin/.conda/envs/vibrant/bin/hgtector", line 30, in main
    args = parse_args(modules)
  File "/public/home/chenruolin/.conda/envs/vibrant/bin/hgtector", line 58, in parse_args
    title='commands', dest='command', required=True)
  File "/public/home/chenruolin/.conda/envs/vibrant/lib/python3.6/argparse.py", line 1703, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
----------------------------------------------------------------------------------
Has anyone been in the same situation? 
Thanks

**Comment by caris1988** [comment]
I reinstalled HGTector. It now works.
